### ISSUE TITLE
maybe wrong Fre-GAN 2 discriminator(MSD)

### ISSUE THREAD

**Issue by y-chan** [prml-lab-speech-team/demo#2]
Hi, I'm y-chan, student at the University of Electro-communications.

Thank you for writing nice paper(Fre-GAN 2) and providing demo code.
I'm studying Fre-GAN2 by reading provided code.

But, I discovered maybe wrong code.
https://github.com/prml-lab-speech-team/demo/blob/2fa7e725b757e62bc1c32edae258a44477a225b7/FreGAN2/code/fregan2.py#L363-L376

Is this code is wrong?

I think the following is correct.

```diff
     yA_hat, yC_hat = self.dwt(y_hat) 
-    yAA_hat, yAC_hat = self.dwt(yA) 
-    yCA_hat, yCC_hat = self.dwt(yC[0]) 
+    yAA_hat, yAC_hat = self.dwt(yA_hat) 
+    yCA_hat, yCC_hat = self.dwt(yC_hat[0]) 
```

Thank you.

**Comment by sh-lee-prml** [comment]
Thank you for correct some error...

I will change it soon
